// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427160716_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EVENT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Movie",
                            Status = "Available",
                            Venue = "The Hobbit"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RESERVATION", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("SEAT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba6a3e71-10b0-4d47-807d-94e6edfacbff"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("b35ad7a5-2ad3-4ae5-86e6-67b533a91edc"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("ed2ff2ad-f583-40fb-98ff-8806aec0c793"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("d682a818-e463-4896-9793-7d804c73f0d5"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("4c59a4d8-e594-4ab5-a710-c4008a2a8467"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("5c0fddae-e0cc-46c2-917b-7f023f6ddff7"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("925c385f-f8f6-4e04-9451-36aa2b209c6c"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("8eb9fddf-1bf0-4453-acad-7dc5074d08b1"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("340bb653-e076-469e-b536-a0d7d336594e"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("8bcc6e1e-4811-445d-816b-05a6669b38e8"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("7c4e21d6-1d2f-4055-aadc-3277157ce312"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0387936-93f8-4802-9443-f49318b564eb"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("f39cbb83-8fb6-4197-8447-2934e863cb56"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("7f4172a0-6bf4-416e-b4d5-8b0ffe262728"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("372f8c58-301c-4217-9774-6cddd8a04f19"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("b04682b1-76fa-48b4-8eb0-f4fc206f3fe5"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("6dcb80d4-29dd-46e6-b376-6598667d2d8c"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("968fe037-bead-4181-b738-33eb8ba3c63a"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("66b02d09-55e0-4a49-bcda-63d3f756b4aa"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("ccb6810b-1265-4274-a194-73fabac39f26"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("94a1f709-dfa7-4d25-9ff6-c4d390a2960e"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("76613e3a-68b1-4360-ae8a-36f085a17ec5"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("213b92b8-7d5f-44de-9995-2ddcae0e68d0"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("c91fadbb-0999-4595-a873-c30f2db91f9e"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("99879152-9eca-4234-9a5b-369d76cb84d9"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0efcc6a-765f-454f-83ed-d5c610280df8"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("3569d2e4-be26-4c37-a706-720f4eb79986"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a72e1a0d-d514-4b02-967a-3a63d8d79835"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("67755d7e-3e5f-4635-8e9d-6a677218119d"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("744b81a1-5cee-4bc9-92b3-af0b65e0a3f4"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("ea41fd34-e108-4da0-9f42-bb918345e2b0"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("94194a7f-80d6-40e3-a24d-0914c487fd4a"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("e42afc8c-5bfb-49f1-b07c-8869ae976b99"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("e42dcf1a-8e90-47a0-a9eb-cb76fd0c1bfd"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("e36400ef-cd88-4347-86be-82e77d1d7972"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("e2f05022-8ad8-4de3-8013-aaf7611ebfd4"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("0364f6e4-a955-4bd6-8a20-a4e3c07d1474"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("f5ed9be5-df8a-4c4f-8cf8-27360d9e38a3"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("797f299c-933e-4047-b417-a5fa147c7c7e"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("e58908af-d0b2-408e-b6da-9036b7a8fac9"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("fa5a958a-71e1-4b8b-bca2-db926388c6d0"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("37e4c2c2-68c7-4035-b535-7a81b360f2bc"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("3ae07be2-b5ce-46b8-bd21-c3c3a7bb3b99"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("2ff47059-c0e3-4da1-82af-1391202d44e5"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("5640aaec-a70c-431a-b7cd-48bd7b18b41e"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("9347e0d4-ae55-4348-b580-fdc6c24c2fac"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("c54cc009-dbfa-40fd-ab2b-501f61076dbf"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("db198071-9843-4baf-b24c-9e653d5c90b0"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("ecd06841-3a4f-4335-9e29-647a5b8cf7c8"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("9ec49cea-81f7-4b58-831b-17278f1b74e7"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("SECTOR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            EventId = 1,
                            Name = "VIP",
                            Price = 800m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1000,
                            EventId = 1,
                            Name = "NORMAL",
                            Price = 450m
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Domain.Entities.User", "UserObj")
                        .WithMany("AuditLogList")
                        .HasForeignKey("UserId");

                    b.Navigation("UserObj");
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Domain.Entities.Seat", "SeatObj")
                        .WithOne("ReservationObj")
                        .HasForeignKey("Domain.Entities.Reservation", "SeatId");

                    b.HasOne("Domain.Entities.User", "UserObj")
                        .WithMany("ReservationList")
                        .HasForeignKey("UserId");

                    b.Navigation("SeatObj");

                    b.Navigation("UserObj");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.HasOne("Domain.Entities.Sector", "SectorObj")
                        .WithMany("SeatsList")
                        .HasForeignKey("SectorId");

                    b.Navigation("SectorObj");
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.HasOne("Domain.Entities.Event", "EventObj")
                        .WithMany("SectorsList")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventObj");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("SectorsList");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Navigation("ReservationObj");
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.Navigation("SeatsList");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogList");

                    b.Navigation("ReservationList");
                });
#pragma warning restore 612, 618
        }
    }
}
