// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514143840_seeds")]
    partial class seeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EVENT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Action",
                            EventDate = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Movie",
                            Status = "Available",
                            Url1 = "https://www.elcineenlasombra.com/wp-content/uploads/2014/12/the-hobbit-the-desolation-of-smaug-22982-2880x1800-copia.jpg",
                            Url2 = "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/6ba42b80-1619-4ed4-b250-0f0718fd3141/f6b2b5af2d4217fca21c52e6b286f67bd78c2d79.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom&w=500",
                            Venue = "The Hobbit"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RESERVATION", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReservationSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("ReservationId", "SeatId")
                        .IsUnique();

                    b.ToTable("RESERVATION_SEAT", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("SEAT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf2d9006-7909-4cd1-93e0-54f8c9c0c138"),
                            RowIdentifier = "A",
                            RowVersion = new byte[0],
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2baa396f-293c-41aa-8b65-b9fab106fb5e"),
                            RowIdentifier = "B",
                            RowVersion = new byte[0],
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7011c175-a118-422d-bba7-888ecd458256"),
                            RowIdentifier = "C",
                            RowVersion = new byte[0],
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bbebe8ac-dcbd-4a12-90cd-5956092f657c"),
                            RowIdentifier = "D",
                            RowVersion = new byte[0],
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("35a375a6-ab29-4479-86be-65e8caaaa641"),
                            RowIdentifier = "E",
                            RowVersion = new byte[0],
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cf64f73f-3e95-4eb5-93e8-793e28c927c1"),
                            RowIdentifier = "A",
                            RowVersion = new byte[0],
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("780b221f-2a3a-43ff-99e2-27f09cfcc93b"),
                            RowIdentifier = "B",
                            RowVersion = new byte[0],
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bc56ec5f-7241-473c-b186-70a35329f7d6"),
                            RowIdentifier = "C",
                            RowVersion = new byte[0],
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("69d2f9a6-8561-4a4f-8abd-7744e31fce6d"),
                            RowIdentifier = "D",
                            RowVersion = new byte[0],
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("117b330b-0468-45a0-8596-a010c2a8d212"),
                            RowIdentifier = "E",
                            RowVersion = new byte[0],
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("69af3ca1-35af-4515-a91b-86efe1a92ce2"),
                            RowIdentifier = "A",
                            RowVersion = new byte[0],
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5db1774e-11bd-49d7-8189-cccca5db892b"),
                            RowIdentifier = "B",
                            RowVersion = new byte[0],
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("37c9859f-4c14-4ef2-93e9-4ded43f4e29b"),
                            RowIdentifier = "C",
                            RowVersion = new byte[0],
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8f1ac601-a31a-46ef-940c-43ed55b243a9"),
                            RowIdentifier = "D",
                            RowVersion = new byte[0],
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c20741f2-818e-42a1-a0c5-bc602155b8b4"),
                            RowIdentifier = "E",
                            RowVersion = new byte[0],
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5b830693-2649-4831-ab12-8606d119bd88"),
                            RowIdentifier = "A",
                            RowVersion = new byte[0],
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("168c6bc5-4075-463e-8c98-e2c2f5f3a3ee"),
                            RowIdentifier = "B",
                            RowVersion = new byte[0],
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("db6e0dc6-30eb-4f9d-879c-e6e93c41a1d0"),
                            RowIdentifier = "C",
                            RowVersion = new byte[0],
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f9c74f85-0337-4da6-8814-15eca3d9013c"),
                            RowIdentifier = "D",
                            RowVersion = new byte[0],
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a8b1c8d9-4c3d-4b4e-b626-23d4bc6d457d"),
                            RowIdentifier = "E",
                            RowVersion = new byte[0],
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("fb0a782a-6f2a-42b0-81d4-ffb085280cbc"),
                            RowIdentifier = "A",
                            RowVersion = new byte[0],
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9e7e9603-942a-47a9-a664-154d33aa2120"),
                            RowIdentifier = "B",
                            RowVersion = new byte[0],
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e5ca8a53-8515-488c-822e-a6793894ad67"),
                            RowIdentifier = "C",
                            RowVersion = new byte[0],
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("646f5236-1dca-4d81-8733-8f731e88fc18"),
                            RowIdentifier = "D",
                            RowVersion = new byte[0],
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("98564824-bc6b-4ce0-abca-8fd2ca7306be"),
                            RowIdentifier = "E",
                            RowVersion = new byte[0],
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("946510b5-6dd8-4c7e-a0d9-dc283605e606"),
                            RowIdentifier = "A",
                            RowVersion = new byte[0],
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3c74e33e-0a33-47c1-bd15-547b63d26fa7"),
                            RowIdentifier = "B",
                            RowVersion = new byte[0],
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("07cbd32c-de75-4c9e-82bd-c5d0288deb09"),
                            RowIdentifier = "C",
                            RowVersion = new byte[0],
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cc5f741c-e4e8-44e3-82c2-18fabd7c4311"),
                            RowIdentifier = "D",
                            RowVersion = new byte[0],
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("063b9ffe-52fa-4acc-bbf7-a2970a4e6fa8"),
                            RowIdentifier = "E",
                            RowVersion = new byte[0],
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ee18d8c8-3d4a-4b30-8390-92ed09dd26a1"),
                            RowIdentifier = "A",
                            RowVersion = new byte[0],
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b886486d-c61d-4eb0-b01b-42a6b30d19f6"),
                            RowIdentifier = "B",
                            RowVersion = new byte[0],
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8292af1e-f408-49a6-b416-35d55eef8baa"),
                            RowIdentifier = "C",
                            RowVersion = new byte[0],
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("12f1e066-489b-4be0-81d4-61d26edc7691"),
                            RowIdentifier = "D",
                            RowVersion = new byte[0],
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6a3749bc-659d-4ae6-806d-74f0ff36e262"),
                            RowIdentifier = "E",
                            RowVersion = new byte[0],
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("fb8573d3-efe8-43df-83ec-411e4f2c1d9c"),
                            RowIdentifier = "A",
                            RowVersion = new byte[0],
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3f2dd947-7228-436c-9e81-f8f1d2b7b3b7"),
                            RowIdentifier = "B",
                            RowVersion = new byte[0],
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8e2738ca-8e9b-4823-ab25-1ebb1291d800"),
                            RowIdentifier = "C",
                            RowVersion = new byte[0],
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("fc357336-ad6c-4d87-9f06-a3c7fa0456b0"),
                            RowIdentifier = "D",
                            RowVersion = new byte[0],
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("324cf69a-df84-491a-9190-8b0aecfd7928"),
                            RowIdentifier = "E",
                            RowVersion = new byte[0],
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("46fdc975-7e20-44cd-8003-cac8f6244c70"),
                            RowIdentifier = "A",
                            RowVersion = new byte[0],
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("96fa876b-50cd-4953-b05b-5c691de9ceba"),
                            RowIdentifier = "B",
                            RowVersion = new byte[0],
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1530e3c3-3771-412a-a410-867f5645e937"),
                            RowIdentifier = "C",
                            RowVersion = new byte[0],
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("692ff031-2ec7-4258-8a72-15ce87ebc37d"),
                            RowIdentifier = "D",
                            RowVersion = new byte[0],
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b1c844f1-d2a7-4999-9fc6-1b0b34d2d1b1"),
                            RowIdentifier = "E",
                            RowVersion = new byte[0],
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("05bd49be-0a08-4091-96f2-390e052fb995"),
                            RowIdentifier = "A",
                            RowVersion = new byte[0],
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8df2c631-96fb-4c3c-b2c1-5c3d24671a34"),
                            RowIdentifier = "B",
                            RowVersion = new byte[0],
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6e9b20ac-2332-4601-a66b-f736b1d248d2"),
                            RowIdentifier = "C",
                            RowVersion = new byte[0],
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("45157000-ac9a-419a-9eae-b211cff6f5ef"),
                            RowIdentifier = "D",
                            RowVersion = new byte[0],
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5f0a8fe4-e4f2-4817-a03f-06932b573257"),
                            RowIdentifier = "E",
                            RowVersion = new byte[0],
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Cols")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("GridX")
                        .HasColumnType("int");

                    b.Property<int>("GridY")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Name")
                        .IsUnique();

                    b.ToTable("SECTOR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            Cols = 5,
                            EventId = 1,
                            GridX = 0,
                            GridY = 0,
                            Name = "VIP",
                            Price = 800m,
                            Rows = 5
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1000,
                            Cols = 5,
                            EventId = 1,
                            GridX = 0,
                            GridY = 0,
                            Name = "NORMAL",
                            Price = 450m,
                            Rows = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Domain.Entities.User", "UserObj")
                        .WithMany("AuditLogList")
                        .HasForeignKey("UserId");

                    b.Navigation("UserObj");
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Domain.Entities.User", "UserObj")
                        .WithMany("ReservationList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserObj");
                });

            modelBuilder.Entity("Domain.Entities.ReservationSeat", b =>
                {
                    b.HasOne("Domain.Entities.Reservation", "ReservationObj")
                        .WithMany("Seats")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seat", "SeatObj")
                        .WithMany("ReservationSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationObj");

                    b.Navigation("SeatObj");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.HasOne("Domain.Entities.Sector", "SectorObj")
                        .WithMany("SeatsList")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SectorObj");
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.HasOne("Domain.Entities.Event", "EventObj")
                        .WithMany("SectorsList")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventObj");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("SectorsList");
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Navigation("ReservationSeats");
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.Navigation("SeatsList");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogList");

                    b.Navigation("ReservationList");
                });
#pragma warning restore 612, 618
        }
    }
}
