// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EVENT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            Name = "concierto de rock",
                            Status = "Available",
                            Venue = "la renga"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RESERVATION", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("SEAT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111001"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111002"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111003"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111004"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111005"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111006"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111007"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111008"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111009"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111010"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111011"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111012"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111013"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111014"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111015"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111016"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111017"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111018"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111019"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111020"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111021"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111022"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111023"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111024"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111025"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111026"),
                            RowIdentifier = "C",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111027"),
                            RowIdentifier = "C",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111028"),
                            RowIdentifier = "C",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111029"),
                            RowIdentifier = "C",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111030"),
                            RowIdentifier = "C",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111031"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111032"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111033"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111034"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111035"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111036"),
                            RowIdentifier = "D",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111037"),
                            RowIdentifier = "D",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111038"),
                            RowIdentifier = "D",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111039"),
                            RowIdentifier = "D",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111040"),
                            RowIdentifier = "D",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111041"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111042"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111043"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111044"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111045"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111046"),
                            RowIdentifier = "E",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111047"),
                            RowIdentifier = "E",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111048"),
                            RowIdentifier = "E",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111049"),
                            RowIdentifier = "E",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111050"),
                            RowIdentifier = "E",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222001"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222002"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222003"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222004"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222005"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222006"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222007"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222008"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222009"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222010"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222011"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222012"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222013"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222014"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222015"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222016"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222017"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222018"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222019"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222020"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222021"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222022"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222023"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222024"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222025"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222026"),
                            RowIdentifier = "C",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222027"),
                            RowIdentifier = "C",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222028"),
                            RowIdentifier = "C",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222029"),
                            RowIdentifier = "C",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222030"),
                            RowIdentifier = "C",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222031"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222032"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222033"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222034"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222035"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222036"),
                            RowIdentifier = "D",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222037"),
                            RowIdentifier = "D",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222038"),
                            RowIdentifier = "D",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222039"),
                            RowIdentifier = "D",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222040"),
                            RowIdentifier = "D",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222041"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222042"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222043"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222044"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222045"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222046"),
                            RowIdentifier = "E",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222047"),
                            RowIdentifier = "E",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222048"),
                            RowIdentifier = "E",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222049"),
                            RowIdentifier = "E",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222050"),
                            RowIdentifier = "E",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("SECTOR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            EventId = 1,
                            Name = "VIP",
                            Price = 800m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1000,
                            EventId = 1,
                            Name = "NORMAL",
                            Price = 450m
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("USER", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@test.com",
                            Name = "Test User",
                            PasswordHash = "1234"
                        });
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Domain.Entities.User", "UserObj")
                        .WithMany("AuditLogList")
                        .HasForeignKey("UserId");

                    b.Navigation("UserObj");
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Domain.Entities.Seat", "SeatObj")
                        .WithOne("ReservationObj")
                        .HasForeignKey("Domain.Entities.Reservation", "SeatId");

                    b.HasOne("Domain.Entities.User", "UserObj")
                        .WithMany("ReservationList")
                        .HasForeignKey("UserId");

                    b.Navigation("SeatObj");

                    b.Navigation("UserObj");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.HasOne("Domain.Entities.Sector", "SectorObj")
                        .WithMany("SeatsList")
                        .HasForeignKey("SectorId");

                    b.Navigation("SectorObj");
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.HasOne("Domain.Entities.Event", "EventObj")
                        .WithMany("SectorsList")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventObj");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("SectorsList");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Navigation("ReservationObj");
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.Navigation("SeatsList");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogList");

                    b.Navigation("ReservationList");
                });
#pragma warning restore 612, 618
        }
    }
}
